// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.1
// source: sample/sample.proto

package sample

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GreeterClient is the client API for Greeter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GreeterClient interface {
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
}

type greeterClient struct {
	cc grpc.ClientConnInterface
}

func NewGreeterClient(cc grpc.ClientConnInterface) GreeterClient {
	return &greeterClient{cc}
}

func (c *greeterClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/sample.Greeter/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GreeterServer is the server API for Greeter service.
// All implementations must embed UnimplementedGreeterServer
// for forward compatibility
type GreeterServer interface {
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
	mustEmbedUnimplementedGreeterServer()
}

// UnimplementedGreeterServer must be embedded to have forward compatible implementations.
type UnimplementedGreeterServer struct {
}

func (UnimplementedGreeterServer) SayHello(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedGreeterServer) mustEmbedUnimplementedGreeterServer() {}

// UnsafeGreeterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GreeterServer will
// result in compilation errors.
type UnsafeGreeterServer interface {
	mustEmbedUnimplementedGreeterServer()
}

func RegisterGreeterServer(s grpc.ServiceRegistrar, srv GreeterServer) {
	s.RegisterService(&Greeter_ServiceDesc, srv)
}

func _Greeter_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sample.Greeter/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Greeter_ServiceDesc is the grpc.ServiceDesc for Greeter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Greeter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sample.Greeter",
	HandlerType: (*GreeterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Greeter_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sample/sample.proto",
}

// RecipienterClient is the client API for Recipienter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RecipienterClient interface {
	GetRecipients(ctx context.Context, in *GetRecipientsRequest, opts ...grpc.CallOption) (*GetRecipientsResponse, error)
}

type recipienterClient struct {
	cc grpc.ClientConnInterface
}

func NewRecipienterClient(cc grpc.ClientConnInterface) RecipienterClient {
	return &recipienterClient{cc}
}

func (c *recipienterClient) GetRecipients(ctx context.Context, in *GetRecipientsRequest, opts ...grpc.CallOption) (*GetRecipientsResponse, error) {
	out := new(GetRecipientsResponse)
	err := c.cc.Invoke(ctx, "/sample.Recipienter/GetRecipients", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RecipienterServer is the server API for Recipienter service.
// All implementations must embed UnimplementedRecipienterServer
// for forward compatibility
type RecipienterServer interface {
	GetRecipients(context.Context, *GetRecipientsRequest) (*GetRecipientsResponse, error)
	mustEmbedUnimplementedRecipienterServer()
}

// UnimplementedRecipienterServer must be embedded to have forward compatible implementations.
type UnimplementedRecipienterServer struct {
}

func (UnimplementedRecipienterServer) GetRecipients(context.Context, *GetRecipientsRequest) (*GetRecipientsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRecipients not implemented")
}
func (UnimplementedRecipienterServer) mustEmbedUnimplementedRecipienterServer() {}

// UnsafeRecipienterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RecipienterServer will
// result in compilation errors.
type UnsafeRecipienterServer interface {
	mustEmbedUnimplementedRecipienterServer()
}

func RegisterRecipienterServer(s grpc.ServiceRegistrar, srv RecipienterServer) {
	s.RegisterService(&Recipienter_ServiceDesc, srv)
}

func _Recipienter_GetRecipients_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRecipientsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecipienterServer).GetRecipients(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sample.Recipienter/GetRecipients",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecipienterServer).GetRecipients(ctx, req.(*GetRecipientsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Recipienter_ServiceDesc is the grpc.ServiceDesc for Recipienter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Recipienter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sample.Recipienter",
	HandlerType: (*RecipienterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRecipients",
			Handler:    _Recipienter_GetRecipients_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sample/sample.proto",
}
